title: "<suggested new type name>"
labels: ["New type"]
body:
- type: textarea
  id: alternative-type-names
  attributes:
    label: Alternative type names
    description: Known synonyms for the same terms type.
    placeholder: | 
      Business Users Privacy Policy
      Commercial Privacy Policy
- type: input
  id: writer
  attributes:
    label: Writer
    description: The author of the document, in most cases the service provider itself.
    placeholder: service provider
- type: input
  id: audience
  attributes:
    label: Audience
    description: The targeted audience whose rights and duties are defined in the associated terms.
    placeholder: business user
- type: input
  id: object
  attributes:
    label: Object
    description: The object of the commitment, i.e. the information or interaction whose handling will be constrained by the associated terms.
    placeholder: personal data of business users
- type: textarea
  id: examples
  attributes:
    label: Examples
    description: |
      Examples of documents that contain terms of the suggested type, in the form `URL - Title - Jurisdiction`, one per line. Provide the URL address at which the document can be accessed; the title of the document provided at this URL; and, if possible, the jurisdiction to which the document refers.
    placeholder: | 
      https://www.whatsapp.com/legal/privacy-policy-eea?lang=en - Privacy Policy - European Economic Area
  validations:
    required: true
- type: textarea
  id: references
  attributes:
    label: References
    description: | 
      Related resources that may help to understand the purpose of this type, such as legal definitions, or the discussions that led to the choice of this name.
    placeholder: "Digital Service Act: https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022R2065"
- type: textarea
  id: comments
  attributes:
    label: Comments
    description: Any additional information that may help to understand the purpose of this type.
