name: Release

on:
  push:
    branches: [ main ]

jobs:
  changelog:
    uses: ./.github/workflows/changelog.yml

  test:
    uses: ./.github/workflows/test.yml

  release:
    if: needs.changelog.outputs.release-type != 'no-release'
    needs: [ changelog, test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update changelog for release
        id: release-changelog
        uses: OpenTermsArchive/changelog-action/release@v0.4.0

      - name: Bump package version
        run: npm --no-git-tag-version version ${{ steps.release-changelog.outputs.version }}

      - name: Update repository
        run: |
          git config user.name "Open Terms Archive Release Bot"
          git config user.email "release-bot@opentermsarchive.org"
          git commit --message="Update changelog and version number" CHANGELOG.md package.json package-lock.json
          git tag v${{ steps.release-changelog.outputs.version }}
          git push origin
          git push --tags

      - name: Publish to NPM public repository
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPMJS_ACCESS_TOKEN }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.release-changelog.outputs.version }}
          body: ${{ steps.release-changelog.outputs.content }}
          token: ${{ secrets.GITHUB_TOKEN }}

  clean-changelog:
    if: needs.changelog.outputs.release-type == 'no-release'
    needs: [ changelog ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update changelog for release
        uses: OpenTermsArchive/changelog-action/release@v0.4.0

      - name: Save changelog
        run: |
          git config user.name "Open Terms Archive Release Bot"
          git config user.email "release-bot@opentermsarchive.org"
          git commit --message="Clean changelog" CHANGELOG.md
          git push origin
