name: Validate document types

on:
  push:
    branches-ignore: [ main ]  # will be called from workflow call
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: npm ci

      - run: npm test
