name: Validate document types

on:
  push:
    branches-ignore: [ test-main ]  # will be called from workflow call
  pull_request:
    types: [ opened, reopened ]
  workflow_call:
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: npm ci

      - run: npm test
